# llamafactory-cli train LLaMA-Factory-configs/train_lora/Llama2_PARAREL.yaml
### model
model_name_or_path: LLaMA-Factory/models/TrustworthyLLM_Cognition_PSQA_Finetuning_Model_0_Merged

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

### dataset
dataset: PARAREL_ID
template: llama2
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: LLaMA-Factory/models/TrustworthyLLM_PARAREL
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

# not report to wandb
report_to: "none"
